# Standalone Mock API Server
# Generated by COM Mock Agent

import json
import logging
import os
import re
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

import uvicorn
from fastapi import FastAPI, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

# ── Logging ──────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)-8s %(message)s")
logger = logging.getLogger("mock-api")

# ── Mock Data Store ──────────────────────────────────────────────────────────

class MockDataStore:
    def __init__(self):
        self.collections = {} # path -> list[dict]
        self.static_responses = {} # "METHOD /path" -> data

    def load(self, endpoints, mock_data):
        for ep in endpoints:
            method = ep.get("method", "GET")
            path = ep.get("path", "")
            key = f"{method} {path}"
            data = mock_data.get(key)

            if method == "GET" and "{" not in path:
                if isinstance(data, dict):
                    items = data.get("members") or data.get("items") or []
                    self.collections[path] = list(items)
                else:
                    self.collections.setdefault(path, [])
                self.static_responses[key] = data
            else:
                self.static_responses[key] = data

    def get_collection(self, path, start=0, count=50, filter_str=None, sort=None):
        items = self.collections.get(path, [])
        if filter_str:
            items = [i for i in items if filter_str.lower() in json.dumps(i).lower()]
        if sort:
            field = sort.split(":")[0].strip()
            reverse = "desc" in sort.lower()
            items = sorted(items, key=lambda x: str(x.get(field, "")), reverse=reverse)
        
        page = items[start : start + count]
        template = self.static_responses.get(f"GET {path}", {}) or {}
        list_key = "members" if "members" in template else "items"
        return {**template, list_key: page, "count": len(page), "total": len(items), "start": start, "uri": path}

    def get_resource(self, collection_path, resource_id):
        for item in self.collections.get(collection_path, []):
            uri = item.get("uri", "")
            if uri.endswith(resource_id) or item.get("uuid") == resource_id or str(item.get("id")) == resource_id:
                return item
        return None

    def create_resource(self, collection_path, data):
        new_id = str(uuid.uuid4()).upper()
        data.setdefault("uri", f"{collection_path}/{new_id}")
        data.setdefault("uuid", new_id)
        now = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
        data.setdefault("created", now)
        data["modified"] = now
        self.collections.setdefault(collection_path, []).append(data)
        return data

    def update_resource(self, collection_path, resource_id, data):
        items = self.collections.get(collection_path, [])
        for i, item in enumerate(items):
            uri = item.get("uri", "")
            if uri.endswith(resource_id) or item.get("uuid") == resource_id or str(item.get("id")) == resource_id:
                now = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
                items[i] = {**item, **data, "modified": now}
                return items[i]
        return None

    def delete_resource(self, collection_path, resource_id):
        items = self.collections.get(collection_path, [])
        for i, item in enumerate(items):
            uri = item.get("uri", "")
            if uri.endswith(resource_id) or item.get("uuid") == resource_id or str(item.get("id")) == resource_id:
                return items.pop(i)
        return None

# ── App Data ─────────────────────────────────────────────────────────────────

API_SPEC = {
  "title": "Petstore API",
  "version": "1.0.0",
  "source_url": "https://petstore.swagger.io/",
  "total_endpoints": 5,
  "total_sections": 1,
  "endpoints": [
    {
      "method": "GET",
      "path": "/api/api",
      "summary": "List all API",
      "category": "GENERAL",
      "subcategory": "API",
      "parameters": [
        {
          "name": "offset",
          "location": "query",
          "param_type": "integer",
          "required": false,
          "description": "Pagination offset"
        },
        {
          "name": "limit",
          "location": "query",
          "param_type": "integer",
          "required": false,
          "description": "Page size"
        },
        {
          "name": "filter",
          "location": "query",
          "param_type": "string",
          "required": false,
          "description": "Filter expression"
        },
        {
          "name": "sort",
          "location": "query",
          "param_type": "string",
          "required": false,
          "description": "Sort field"
        }
      ],
      "response_example": {
        "items": [
          {
            "id": "4b95b677-0a44-478a-3f42-8faf6a561257",
            "type": "api",
            "uri": "/api/api/4b95b677-0a44-478a-3f42-8faf6a561257",
            "name": "Primary API 1",
            "description": "Auto-generated sample api instance #1",
            "status": "active",
            "created": "2025-06-01T00:30:00.000Z",
            "modified": "2025-06-01T00:45:00.000Z"
          },
          {
            "id": "570e3260-1dfa-9f10-f1af-bbce26770716",
            "type": "api",
            "uri": "/api/api/570e3260-1dfa-9f10-f1af-bbce26770716",
            "name": "Secondary API 2",
            "description": "Auto-generated sample api instance #2",
            "status": "inactive",
            "created": "2025-06-02T03:30:00.000Z",
            "modified": "2025-06-02T03:45:00.000Z"
          },
          {
            "id": "bb29f6a9-b2fc-3382-a95c-b6874f29b722",
            "type": "api",
            "uri": "/api/api/bb29f6a9-b2fc-3382-a95c-b6874f29b722",
            "name": "Backup API 3",
            "description": "Auto-generated sample api instance #3",
            "status": "provisioning",
            "created": "2025-06-03T06:30:00.000Z",
            "modified": "2025-06-03T06:45:00.000Z"
          }
        ],
        "count": 3,
        "total": 3,
        "offset": 0,
        "uri": "/api/api"
      }
    },
    {
      "method": "GET",
      "path": "/api/api/{id}",
      "summary": "Get API by ID",
      "category": "GENERAL",
      "subcategory": "API",
      "parameters": [
        {
          "name": "id",
          "location": "path",
          "param_type": "string",
          "required": true,
          "description": "API identifier"
        }
      ],
      "response_example": {
        "id": "4b95b677-0a44-478a-3f42-8faf6a561257",
        "type": "api",
        "uri": "/api/api/4b95b677-0a44-478a-3f42-8faf6a561257",
        "name": "Primary API 1",
        "description": "Auto-generated sample api instance #1",
        "status": "active",
        "created": "2025-06-01T00:30:00.000Z",
        "modified": "2025-06-01T00:45:00.000Z"
      }
    },
    {
      "method": "POST",
      "path": "/api/api",
      "summary": "Create API",
      "category": "GENERAL",
      "subcategory": "API",
      "parameters": [],
      "request_body": {
        "name": "New API"
      },
      "response_example": {
        "id": "new-resource-uuid",
        "type": "api",
        "uri": "/api/api/4b95b677-0a44-478a-3f42-8faf6a561257",
        "name": "Primary API 1",
        "description": "Auto-generated sample api instance #1",
        "status": "active",
        "created": "2025-06-01T00:30:00.000Z",
        "modified": "2025-06-01T00:45:00.000Z"
      }
    },
    {
      "method": "PUT",
      "path": "/api/api/{id}",
      "summary": "Update API",
      "category": "GENERAL",
      "subcategory": "API",
      "parameters": [
        {
          "name": "id",
          "location": "path",
          "param_type": "string",
          "required": true,
          "description": "API identifier"
        }
      ],
      "request_body": {
        "name": "Updated API"
      },
      "response_example": {
        "id": "4b95b677-0a44-478a-3f42-8faf6a561257",
        "type": "api",
        "uri": "/api/api/4b95b677-0a44-478a-3f42-8faf6a561257",
        "name": "Primary API 1",
        "description": "Auto-generated sample api instance #1",
        "status": "active",
        "created": "2025-06-01T00:30:00.000Z",
        "modified": "2025-06-01T00:45:00.000Z"
      }
    },
    {
      "method": "DELETE",
      "path": "/api/api/{id}",
      "summary": "Delete API",
      "category": "GENERAL",
      "subcategory": "API",
      "parameters": [
        {
          "name": "id",
          "location": "path",
          "param_type": "string",
          "required": true,
          "description": "API identifier"
        }
      ],
      "response_example": null
    }
  ],
  "sections": [
    {
      "name": "API",
      "category_group": "GENERAL",
      "url": "https://petstore.swagger.io/"
    }
  ]
}
MOCK_DATA = {
  "GET /api/api": {
    "items": [
      {
        "id": "4b95b677-0a44-478a-3f42-8faf6a561257",
        "type": "api",
        "uri": "/api/api/4b95b677-0a44-478a-3f42-8faf6a561257",
        "name": "Primary API 1",
        "description": "Auto-generated sample api instance #1",
        "status": "active",
        "created": "2025-06-01T00:30:00.000Z",
        "modified": "2025-06-01T00:45:00.000Z"
      },
      {
        "id": "570e3260-1dfa-9f10-f1af-bbce26770716",
        "type": "api",
        "uri": "/api/api/570e3260-1dfa-9f10-f1af-bbce26770716",
        "name": "Secondary API 2",
        "description": "Auto-generated sample api instance #2",
        "status": "inactive",
        "created": "2025-06-02T03:30:00.000Z",
        "modified": "2025-06-02T03:45:00.000Z"
      },
      {
        "id": "bb29f6a9-b2fc-3382-a95c-b6874f29b722",
        "type": "api",
        "uri": "/api/api/bb29f6a9-b2fc-3382-a95c-b6874f29b722",
        "name": "Backup API 3",
        "description": "Auto-generated sample api instance #3",
        "status": "provisioning",
        "created": "2025-06-03T06:30:00.000Z",
        "modified": "2025-06-03T06:45:00.000Z"
      }
    ],
    "count": 3,
    "total": 3,
    "offset": 0,
    "uri": "/api/api"
  },
  "GET /api/api/{id}": {
    "id": "4b95b677-0a44-478a-3f42-8faf6a561257",
    "type": "api",
    "uri": "/api/api/4b95b677-0a44-478a-3f42-8faf6a561257",
    "name": "Primary API 1",
    "description": "Auto-generated sample api instance #1",
    "status": "active",
    "created": "2025-06-01T00:30:00.000Z",
    "modified": "2025-06-01T00:45:00.000Z"
  },
  "POST /api/api": {
    "id": "new-resource-uuid",
    "type": "api",
    "uri": "/api/api/4b95b677-0a44-478a-3f42-8faf6a561257",
    "name": "Primary API 1",
    "description": "Auto-generated sample api instance #1",
    "status": "active",
    "created": "2025-06-01T00:30:00.000Z",
    "modified": "2025-06-01T00:45:00.000Z"
  },
  "PUT /api/api/{id}": {
    "id": "4b95b677-0a44-478a-3f42-8faf6a561257",
    "type": "api",
    "uri": "/api/api/4b95b677-0a44-478a-3f42-8faf6a561257",
    "name": "Primary API 1",
    "description": "Auto-generated sample api instance #1",
    "status": "active",
    "created": "2025-06-01T00:30:00.000Z",
    "modified": "2025-06-01T00:45:00.000Z"
  },
  "DELETE /api/api/{id}": null
}

# ── App Setup ────────────────────────────────────────────────────────────────

app = FastAPI(
    title=API_SPEC.get("title", "Mock API") + " (Standalone)",
    description="Generated Standalone Mock Server",
    version=API_SPEC.get("version", "1.0.0")
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

store = MockDataStore()
store.load(API_SPEC.get("endpoints", []), MOCK_DATA)

# ── Routes ───────────────────────────────────────────────────────────────────

@app.get("/")
async def root():
    return {
        "title": API_SPEC.get("title"),
        "version": API_SPEC.get("version"),
        "endpoints_count": len(API_SPEC.get("endpoints", [])),
        "docs": "/docs"
    }

@app.api_route("/{path:path}", methods=["GET", "POST", "PUT", "PATCH", "DELETE"], include_in_schema=False)
async def catch_all(request: Request, path: str, start: int = 0, count: int = 50, filter: Optional[str] = None):
    full_path = request.url.path
    method = request.method
    
    # ── 1. Exact Match ───────────────────────────────────────────
    key = f"{method} {full_path}"
    if full_path in store.collections and method == "GET":
        return JSONResponse(store.get_collection(full_path, start, count, filter))
    
    if key in MOCK_DATA:
        if method == "POST":
            body = await request.json() if request.get("content-type") == "application/json" else {}
            return JSONResponse(store.create_resource(full_path, body), status_code=201)
        return JSONResponse(MOCK_DATA[key])

    # ── 2. Pattern Match ─────────────────────────────────────────
    for ep in API_SPEC.get("endpoints", []):
        if ep["method"] != method or "{" not in ep["path"]:
            continue
        
        # Simple regex conversion
        regex_pattern = re.sub(r"\{(\w+)\}", r"(?P<\1>[^/]+)", ep["path"])
        match = re.match(f"^{regex_pattern}$", full_path)
        if match:
            resource_id = match.groupdict().get("id", "")
            collection_path = re.sub(r"/\{[^}]+\}$", "", ep["path"])
            
            if method == "GET":
                res = store.get_resource(collection_path, resource_id)
                return JSONResponse(res) if res else JSONResponse({"error": "Not Found"}, status_code=404)
            elif method in ("PUT", "PATCH"):
                body = await request.json()
                res = store.update_resource(collection_path, resource_id, body)
                return JSONResponse(res) if res else JSONResponse({"error": "Not Found"}, status_code=404)
            elif method == "DELETE":
                res = store.delete_resource(collection_path, resource_id)
                return JSONResponse(None, status_code=204) if res else JSONResponse({"error": "Not Found"}, status_code=404)

    return JSONResponse({"error": "Not Found", "path": full_path}, status_code=404)

if __name__ == "__main__":
    port = int(os.getenv("PORT", 8080))
    uvicorn.run(app, host="0.0.0.0", port=port)
